name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "31 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.5.0
        env:
          GITHUB_TOKEN: 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
          USERNAME: ${{ github.sensationalshubham }}
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name Shubham Bansal
          git config user.email bansal4995@gmail.com
          git add -A .
          git commit -m "generated"
          git push
